In [39]:
from app.models.models import AssetTransaction

In [209]:
import requests
import pandas as pd
API_URL = "http://localhost:8000"


list_ativos_exemplo = [
 {'data':'2022-12-21', 'categoria':'Ações','codigo_ativo': 'ITSA4.SA','quantidade': 58.0,'valor_unitario': 8.39,'valor_compra': 486.04, 'evento':'Compra'},
 {'data':'2023-02-09', 'categoria':'Ações','codigo_ativo': 'SAPR4.SA','quantidade': 28.0,'valor_unitario': 3.47,'valor_compra': 96.88, 'evento':'Compra'},
 {'data':'2023-02-09', 'categoria':'Ações','codigo_ativo': 'CPLE6.SA','quantidade': 13.0,'valor_unitario': 7.53,'valor_compra': 95.55, 'evento':'Compra'},
 {'data':'2023-02-14', 'categoria':'Ações','codigo_ativo': 'BBAS3.SA','quantidade': 7.0,'valor_unitario': 40.59,'valor_compra': 284.2, 'evento':'Compra'},
 {'data':'2023-02-13', 'categoria':'Ações','codigo_ativo': 'BBDC3.SA','quantidade': 25.0,'valor_unitario': 11.59,'valor_compra': 295.5, 'evento':'Compra'},
 {'data':'2023-02-14', 'categoria':'Ações','codigo_ativo': 'BBSE3.SA','quantidade': 8.0,'valor_unitario': 36.34,'valor_compra': 290.0, 'evento':'Compra'},
 {'data':'2023-02-14', 'categoria':'FII','codigo_ativo': 'BRCO11.SA','quantidade': 1.0,'valor_unitario': 93.12,'valor_compra': 93.56, 'evento':'Compra'},
 {'data':'2023-02-14', 'categoria':'FII','codigo_ativo': 'HGCR11.SA','quantidade': 1.0,'valor_unitario': 99.81,'valor_compra': 100.23, 'evento':'Compra'},
 {'data':'2023-02-14', 'categoria':'FII','codigo_ativo': 'IRDM11.SA','quantidade': 1.0,'valor_unitario': 88.68,'valor_compra': 89.62, 'evento':'Compra'},
 {'data':'2023-02-14', 'categoria':'Ações','codigo_ativo': 'ITUB3.SA','quantidade': 13.0,'valor_unitario': 22.70,'valor_compra': 296.01, 'evento':'Compra'},
 {'data':'2023-02-14', 'categoria':'Ações','codigo_ativo': 'VALE3.SA','quantidade': 3.0,'valor_unitario': 86.70,'valor_compra': 259.77, 'evento':'Compra'},
 {'data':'2023-02-14', 'categoria':'Ações','codigo_ativo': 'WEGE3.SA','quantidade': 7.0,'valor_unitario': 38.58,'valor_compra': 268.8, 'evento':'Compra'},
 {'data':'2023-03-09', 'categoria':'FII','codigo_ativo': 'BCRI11.SA','quantidade': 3.0,'valor_unitario': 86.15,'valor_compra': 258.53, 'evento':'Compra'},
 {'data':'2023-03-09', 'categoria':'FII','codigo_ativo': 'PORD11.SA','quantidade': 3.0,'valor_unitario': 85.94,'valor_compra': 257.84, 'evento':'Compra'},
 {'data':'2023-03-09', 'categoria':'FII','codigo_ativo': 'MXRF11.SA','quantidade': 46.0,'valor_unitario': 10.23,'valor_compra': 472.1, 'evento':'Compra'},
 {'data':'2023-07-10', 'categoria':'FII','codigo_ativo': 'MXRF11.SA','quantidade': 9.0,'valor_unitario': 10.67,'valor_compra': 96.07, 'evento':'Compra'},
 {'data':'2023-07-04', 'categoria':'FII','codigo_ativo': 'HABT11.SA','quantidade': 10.0,'valor_unitario': 95.11,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-08-04', 'categoria':'FII','codigo_ativo': 'JPPA11.SA','quantidade': 10.0,'valor_unitario': 98.55,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-08-04', 'categoria':'FII','codigo_ativo': 'VGIR11.SA','quantidade': 100.0,'valor_unitario': 9.82,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-08-04', 'categoria':'FII','codigo_ativo': 'MXRF11.SA','quantidade': 100.0,'valor_unitario': 10.67,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-08-04', 'categoria':'FII','codigo_ativo': 'OUJP11.SA','quantidade': 10.0,'valor_unitario': 100.30,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-11-23', 'categoria':'FII','codigo_ativo': 'GALG11.SA','quantidade': 52.0,'valor_unitario': 9.42,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-11-23', 'categoria':'FII','codigo_ativo': 'MXRF11.SA','quantidade': 50.0,'valor_unitario': 10.94,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-11-23', 'categoria':'Ações','codigo_ativo': 'SAPR4.SA','quantidade': 28.0,'valor_unitario': 5.13,'valor_compra': None, 'evento':'Venda'},
 {'data':'2023-11-23', 'categoria':'Ações','codigo_ativo': 'VALE3.SA','quantidade': 3.0,'valor_unitario': 74.23,'valor_compra': None, 'evento':'Venda'},
 {'data':'2023-11-23', 'categoria':'Ações','codigo_ativo': 'WEGE3.SA','quantidade': 7.0,'valor_unitario': 33.93,'valor_compra': None, 'evento':'Venda'},
 {'data':'2023-11-27', 'categoria':'FII','codigo_ativo': 'KNCR11.SA','quantidade': 5.0,'valor_unitario': 102.42,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-11-28', 'categoria':'FII','codigo_ativo': 'JPPA11.SA','quantidade': 2.0,'valor_unitario': 91.13,'valor_compra': None, 'evento':'Compra'},
 {'data':'2023-11-28', 'categoria':'FII','codigo_ativo': 'HABT11.SA','quantidade': 3.0,'valor_unitario': 87.40,'valor_compra': None, 'evento':'Compra'},
]

df_ativos_exemplo = pd.DataFrame(list_ativos_exemplo)

In [ ]:
def login(email, password):
    data = {"username": email, "password": password}
    response = requests.post(f"{API_URL}/auth/token", data=data)
    return response.json()

def signup(name, email, password):
    response = requests.post(f"{API_URL}/auth/signup", json={
        "name": name,
        "email": email, 
        "password": password})
    return response.json()

def create_portfolio(access_token):
    json = {
        "name": "string",
    }
    headers = {"Authorization": f"Bearer {access_token}"}
    response = requests.post(f"{API_URL}/portfolio/create", json=json, headers=headers)
    return response.json()

def list_portfolios(access_token):
    headers = {"Authorization": f"Bearer {access_token}"}
    response = requests.get(f"{API_URL}/portfolio/list", headers=headers)
    return response.json()


user_exemple = {"name": "GuiBrand", "email": "guilhermeexemple2@gmail.com", "password": "#1234Abcd"}
registred = signup(**user_exemple)
user = login(email=user_exemple["email"], password=user_exemple["password"])
access_token = user['access_token']

created_poetfolio = create_portfolio(access_token=access_token)
my_portfolios = list_portfolios(access_token=access_token)

my_portfolios

[{'id': 4,
  'description': None,
  'updated_at': '2025-01-11T12:02:57',
  'name': 'string',
  'user_id': 9,
  'created_at': '2025-01-11T12:02:57'}]

In [227]:
from datetime import datetime

def add_transaction(access_token, data):
    headers = {"Authorization": f"Bearer {access_token}"}
    response = requests.post(f"{API_URL}/portfolio/transaction/add", json=data, headers=headers)
    return response.json()

response = requests.get(f"{API_URL}/portfolio/asset/list")
list_asset = response.json()
dict_asset = {asset['symbol']:asset['id'] for asset in list_asset}
enum_transaction_type = {"Compra": 0, "Venda": 1}

for data_ativo in list_ativos_exemplo:
    data = {
    "quantity": data_ativo["quantidade"],
    "unit_value": data_ativo["valor_unitario"],
    "purchase_value": data_ativo["quantidade"] * data_ativo["valor_unitario"],
    "date": data_ativo["data"],
    "portfolio_id": my_portfolios[0]['id'],
    "transaction_type_id": enum_transaction_type.get(data_ativo["evento"]),
    "asset_id": dict_asset[data_ativo["codigo_ativo"]],
    }

    add_transaction(data=data, access_token=access_token)

----

Informações sobre uma carteira especifica

In [232]:
response = requests.get(f"{API_URL}/portfolio/transaction/{my_portfolios[0]['id']}")


response = requests.get(f"{API_URL}/portfolio/transaction/history/{my_portfolios[0]['id']}")

response.json()

[{'id': 68,
  'quantity': 58,
  'unit_value': 8.39,
  'purchase_value': 486.62,
  'date': '2022-12-21T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 18},
 {'id': 69,
  'quantity': 28,
  'unit_value': 3.47,
  'purchase_value': 97.16000000000001,
  'date': '2023-02-09T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 38},
 {'id': 70,
  'quantity': 13,
  'unit_value': 7.53,
  'purchase_value': 97.89,
  'date': '2023-02-09T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 3},
 {'id': 72,
  'quantity': 25,
  'unit_value': 11.59,
  'purchase_value': 289.75,
  'date': '2023-02-13T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 9},
 {'id': 71,
  'quantity': 7,
  'unit_value': 40.59,
  'purchase_value': 284.13,
  'date': '2023-02-14T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 11},
 {'id': 73,
  'quantity': 8,
  'unit_value': 36.34,
  'purchase_value': 290.72,
  'date': '2023-02-14T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 25},
 {'id': 74,
  'quantity': 1,
  'unit_value': 93.12,
  'purchase_value': 93.12,
  'date': '2023-02-14T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 21},
 {'id': 75,
  'quantity': 1,
  'unit_value': 99.81,
  'purchase_value': 99.81,
  'date': '2023-02-14T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 34},
 {'id': 76,
  'quantity': 1,
  'unit_value': 88.68,
  'purchase_value': 88.68,
  'date': '2023-02-14T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 27},
 {'id': 77,
  'quantity': 13,
  'unit_value': 22.7,
  'purchase_value': 295.09999999999997,
  'date': '2023-02-14T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 2},
 {'id': 78,
  'quantity': 3,
  'unit_value': 86.7,
  'purchase_value': 260.1,
  'date': '2023-02-14T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 13},
 {'id': 79,
  'quantity': 7,
  'unit_value': 38.58,
  'purchase_value': 270.06,
  'date': '2023-02-14T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 51},
 {'id': 81,
  'quantity': 3,
  'unit_value': 85.94,
  'purchase_value': 257.82,
  'date': '2023-03-09T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 14},
 {'id': 82,
  'quantity': 46,
  'unit_value': 10.23,
  'purchase_value': 470.58000000000004,
  'date': '2023-03-09T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 31},
 {'id': 80,
  'quantity': 3,
  'unit_value': 86.15,
  'purchase_value': 258.45000000000005,
  'date': '2023-03-09T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 8},
 {'id': 84,
  'quantity': 10,
  'unit_value': 95.11,
  'purchase_value': 951.1,
  'date': '2023-07-04T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 32},
 {'id': 83,
  'quantity': 9,
  'unit_value': 10.67,
  'purchase_value': 96.03,
  'date': '2023-07-10T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 31},
 {'id': 85,
  'quantity': 10,
  'unit_value': 98.55,
  'purchase_value': 985.5,
  'date': '2023-08-04T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 33},
 {'id': 86,
  'quantity': 100,
  'unit_value': 9.82,
  'purchase_value': 982.0,
  'date': '2023-08-04T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 42},
 {'id': 87,
  'quantity': 100,
  'unit_value': 10.67,
  'purchase_value': 1067.0,
  'date': '2023-08-04T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 31},
 {'id': 88,
  'quantity': 10,
  'unit_value': 100.3,
  'purchase_value': 1003.0,
  'date': '2023-08-04T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 10},
 {'id': 89,
  'quantity': 52,
  'unit_value': 9.42,
  'purchase_value': 489.84,
  'date': '2023-11-23T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 19},
 {'id': 90,
  'quantity': 50,
  'unit_value': 10.94,
  'purchase_value': 547.0,
  'date': '2023-11-23T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 31},
 {'id': 91,
  'quantity': 28,
  'unit_value': 5.13,
  'purchase_value': 143.64,
  'date': '2023-11-23T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 1,
  'asset_id': 38},
 {'id': 92,
  'quantity': 3,
  'unit_value': 74.23,
  'purchase_value': 222.69,
  'date': '2023-11-23T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 1,
  'asset_id': 13},
 {'id': 93,
  'quantity': 7,
  'unit_value': 33.93,
  'purchase_value': 237.51,
  'date': '2023-11-23T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 1,
  'asset_id': 51},
 {'id': 94,
  'quantity': 5,
  'unit_value': 102.42,
  'purchase_value': 512.1,
  'date': '2023-11-27T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 16},
 {'id': 95,
  'quantity': 2,
  'unit_value': 91.13,
  'purchase_value': 182.26,
  'date': '2023-11-28T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 33},
 {'id': 96,
  'quantity': 3,
  'unit_value': 87.4,
  'purchase_value': 262.20000000000005,
  'date': '2023-11-28T00:00:00',
  'portfolio_id': 4,
  'transaction_type_id': 0,
  'asset_id': 32}]

In [233]:
pd.DataFrame(response.json())

,id,quantity,unit_value,purchase_value,date,portfolio_id,transaction_type_id,asset_id
0,68,58,8.39,486.62,2022-12-21T00:00:00,4,0,18
1,69,28,3.47,97.16,2023-02-09T00:00:00,4,0,38
2,70,13,7.53,97.89,2023-02-09T00:00:00,4,0,3
3,72,25,11.59,289.75,2023-02-13T00:00:00,4,0,9
4,71,7,40.59,284.13,2023-02-14T00:00:00,4,0,11
5,73,8,36.34,290.72,2023-02-14T00:00:00,4,0,25
6,74,1,93.12,93.12,2023-02-14T00:00:00,4,0,21
7,75,1,99.81,99.81,2023-02-14T00:00:00,4,0,34
8,76,1,88.68,88.68,2023-02-14T00:00:00,4,0,27
9,77,13,22.70,295.10,2023-02-14T00:00:00,4,0,2
10,78,3,86.70,260.10,2023-02-14T00:00:00,4,0,13
11,79,7,38.58,270.06,2023-02-14T00:00:00,4,0,51
12,81,3,85.94,257.82,2023-03-09T00:00:00,4,0,14
13,82,46,10.23,470.58,2023-03-09T00:00:00,4,0,31
14,80,3,86.15,258.45,2023-03-09T00:00:00,4,0,8
15,84,10,95.11,951.10,2023-07-04T00:00:00,4,0,32
16,83,9,10.67,96.03,2023-07-10T00:00:00,4,0,31
17,85,10,98.55,985.50,2023-08-04T00:00:00,4,0,33
18,86,100,9.82,982.00,2023-08-04T00:00:00,4,0,42
19,87,100,10.67,1067.00,2023-08-04T00:00:00,4,0,31
20,88,10,100.30,1003.00,2023-08-04T00:00:00,4,0,10
21,89,52,9.42,489.84,2023-11-23T00:00:00,4,0,19
22,90,50,10.94,547.00,2023-11-23T00:00:00,4,0,31
23,91,28,5.13,143.64,2023-11-23T00:00:00,4,1,38
24,92,3,74.23,222.69,2023-11-23T00:00:00,4,1,13
25,93,7,33.93,237.51,2023-11-23T00:00:00,4,1,51
26,94,5,102.42,512.10,2023-11-27T00:00:00,4,0,16
27,95,2,91.13,182.26,2023-11-28T00:00:00,4,0,33
28,96,3,87.40,262.20,2023-11-28T00:00:00,4,0,32

In [234]:
"""Quero um gráfico de evolução de patrimonio, use dados ficticios para simular a evolução do patrimonio ao longo do tempo"""

response = requests.get(f"{API_URL}/portfolio/transaction/history/{my_portfolios[0]['id']}")
df = pd.DataFrame(response.json())
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(by='date')
df['patrimony'] = df['patrimony'].astype(float)
df['patrimony'].plot()

KeyError: 'patrimony'